services:

    Dontdrinkandroot\BootstrapBundle\Menu\Bs5NavbarRenderer:
        arguments:
            - '@knp_menu.matcher'
            - '@translator'
            - "%knp_menu.renderer.list.options%"
            - "%kernel.charset%"
        tags:
            - { name: knp_menu.renderer, alias: ddr_navbar_bs5 }
