services:

    Dontdrinkandroot\BootstrapBundle\Menu\Bs5DropdownMenuRenderer:
        arguments:
            #            - '@knp_menu.matcher'
            #            - "%knp_menu.renderer.list.options%"
            - '@translator'
            - "%kernel.charset%"
        tags:
            - { name: knp_menu.renderer, alias: ddr_bs5_dropdown_menu }

    Dontdrinkandroot\BootstrapBundle\Menu\Bs5NavbarRenderer:
        arguments:
            - '@knp_menu.matcher'
            - '@translator'
            - '@Dontdrinkandroot\BootstrapBundle\Menu\Bs5DropdownMenuRenderer'
            - "%knp_menu.renderer.list.options%"
            - "%kernel.charset%"
        tags:
            - { name: knp_menu.renderer, alias: ddr_navbar_bs5 }
